INSERT INTO album
(title, artist, price)
VALUES
    ('Certified Lover Boy', 'Drake', 59.99),
    ('Scorpion', 'Drake', 64.99),
    ('Her Loss', 'Drake & 21 Savage', 57.99),
    ('Dark Lane Demo Tapes', 'Drake', 62.99),
    ('Views', 'Drake', 58.99),
    ('More Life', 'Drake', 53.99),
    ('Take Care', 'Drake', 55.99),
    ('Honestly, Nevermind', 'Drake', 66.99),
    ('Astroworld', 'Travis Scott', 61.99),
    ('Utopia', 'Travis Scott', 64.99),
    ('Birds in the Trap Sing McKnight', 'Travis Scott', 59.99),
    ('JackBoys', 'Travis Scott', 51.99),
    ('Rodeo', 'Travis Scott', 60.99),
    ('Huncho Jack, Jack Huncho', 'Travis Scott & Quavo', 63.99),
    ('DAMN.', 'Kendrick Lamar', 55.99),
    ('Mr. Morale & the Big Steppers', 'Kendrick Lamar', 69.99),
    ('Good Kid, M.A.A.D City', 'Kendrick Lamar', 59.99),
    ('To Pimp a Butterfly', 'Kendrick Lamar', 67.99),
    ('Section.80', 'Kendrick Lamar', 57.99),
    ('Black Panther: The Album', 'Kendrick Lamar', 65.99),
    ('The Off-Season', 'J. Cole', 60.99),
    ('KOD', 'J. Cole', 59.99),
    ('2014 Forest Hills Drive', 'J. Cole', 61.99),
    ('4 Your Eyez Only', 'J. Cole', 58.99),
    ('Born Sinner', 'J. Cole', 54.99),
    ('Revenge of the Dreamers III', 'J. Cole & Dreamville', 52.99),
    ('Donda', 'Kanye West', 66.99),
    ('The Life of Pablo', 'Kanye West', 63.99),
    ('Ye', 'Kanye West', 59.99),
    ('Graduation', 'Kanye West', 57.99),
    ('My Beautiful Dark Twisted Fantasy', 'Kanye West', 67.99),
    ('808s & Heartbreak', 'Kanye West', 62.99),
    ('Yeezus', 'Kanye West', 61.99),
    ('Late Registration', 'Kanye West', 59.99),
    ('Jesus Is King', 'Kanye West', 65.99),
    ('Daystar', 'Tory Lanez', 56.99),
    ('Playboy', 'Tory Lanez', 52.99),
    ('Chixtape 5', 'Tory Lanez', 54.99),
    ('Memories Don’t Die', 'Tory Lanez', 60.99),
    ('Love Me Now?', 'Tory Lanez', 59.99),
    ('The New Toronto 3', 'Tory Lanez', 53.99),
    ('I Told You', 'Tory Lanez', 61.99),
    ('Certified Lover Boy', 'Drake', 64.99),
    ('What a Time to Be Alive', 'Drake & Future', 60.99),
    ('So Much Fun', 'Young Thug', 55.99),
    ('Slime Language 2', 'Young Thug & YSL', 63.99),
    ('Punk', 'Young Thug', 57.99),
    ('Jeffery', 'Young Thug', 61.99),
    ('Beautiful Thugger Girls', 'Young Thug', 53.99),
    ('Barter 6', 'Young Thug', 52.99),
    ('Slime Season 3', 'Young Thug', 51.99),
    ('Wunna', 'Gunna', 58.99),
    ('Drip or Drown 2', 'Gunna', 55.99),
    ('DS4Ever', 'Gunna', 59.99),
    ('Drip Season 3', 'Gunna', 60.99),
    ('Drip Harder', 'Lil Baby & Gunna', 62.99),
    ('Harder Than Ever', 'Lil Baby', 64.99),
    ('My Turn', 'Lil Baby', 57.99),
    ('It’s Only Me', 'Lil Baby', 59.99),
    ('Street Gossip', 'Lil Baby', 55.99),
    ('Perfect Timing', 'Lil Baby & Lil Durk', 58.99),
    ('No Love Lost', 'Blxst', 53.99),
    ('Before You Go', 'Blxst', 56.99),
    ('Toxic', 'YG', 60.99),
    ('Still Brazy', 'YG', 61.99),
    ('Stay Dangerous', 'YG', 58.99),
    ('4Real 4Real', 'YG', 57.99),
    ('My Krazy Life', 'YG', 62.99),
    ('I Got Issues', 'YG', 63.99),
    ('High Off Life', 'Future', 55.99),
    ('The WIZRD', 'Future', 58.99),
    ('Future Hndrxx Presents: The WIZRD', 'Future', 61.99),
    ('Beastmode 2', 'Future', 53.99),
    ('Evol', 'Future', 56.99),
    ('Dirty Sprite 2', 'Future', 59.99),
    ('Life of a Don', 'Don Toliver', 61.99),
    ('Heaven or Hell', 'Don Toliver', 58.99),
    ('Love Sick', 'Don Toliver', 57.99),
    ('NAV', 'NAV', 54.99),
    ('Demons Protected by Angels', 'NAV', 60.99),
    ('Bad Habits', 'NAV', 55.99),
    ('Good Intentions', 'NAV', 62.99),
    ('Perfect Timing', 'NAV & Metro Boomin', 59.99),
    ('Heroes & Villains', 'Metro Boomin', 63.99),
    ('Savage Mode II', '21 Savage & Metro Boomin', 66.99),
    ('Not All Heroes Wear Capes', 'Metro Boomin', 60.99),
    ('Without Warning', '21 Savage & Metro Boomin', 59.99),
    ('Issa Album', '21 Savage', 61.99),
    ('I Am > I Was', '21 Savage', 62.99),
    ('Savage Mode', '21 Savage & Metro Boomin', 58.99),
    ('The World Is Yours', 'Rich the Kid', 55.99),
    ('The World Is Yours 2', 'Rich the Kid', 56.99),
    ('Bawskee 4', 'Comethazine', 54.99),
    ('Bawskee 3.5', 'Comethazine', 52.99),
    ('Die Lit', 'Playboi Carti', 61.99),
    ('Whole Lotta Red', 'Playboi Carti', 65.99),
    ('CTRL', 'SZA', 63.99),
    ('SOS', 'SZA', 66.99),
    ('Still Over It', 'Summer Walker', 59.99),
    ('Over It', 'Summer Walker', 58.99);
